feat: allow customizing stryker directory and branch name
tverhoken/stryker-diff-runner pull request #25
Opened 2020-10-28 22:44 UTC by PauloGoncalvesBH

'--path' and '--branch' commands will allow multiple projects to use the library.

@tverhoken Due to my weak knowledge in .ts I was unable to create the tests, I'm sorry for that.
My English is weak, if you believe that you need to adjust some syntax, please inform me about it.

This PR will be very good for my project (https://github.com/PauloGoncalvesBH/ServeRest) and it is what is missing for me to use this great library.

fix #1
fix #2

2020-10-29 02:09 UTC, PauloGoncalvesBH commented
@tverhoken if you don't have a lot of time, what do you think about adding me as a collaborator? I can help maintain the stryker-diff-runner project and build pipelines for continuous delivery.

2020-10-29 08:18 UTC, tverhoken commented
Hello @PauloGoncalvesBH,

Thanks a lot for contributing to this repository. I must confess that I did not take care enough about this project's update (@stryker-mutator/core is up to version 4.0.0 and here is still stuck to 2.0.1 😬 ).

No problem about the `.ts` syntax and tests. If it's ok for you I can suggest an example or we could try some pair programming to do it in order to satisfy minimum project quality.



> @tverhoken if you don't have a lot of time, what do you think about adding me as a collaborator? I can help maintain the stryker-diff-runner project and build pipelines for continuous delivery.

Why not. Let's talk about it once that PR is done 😉

2020-10-29 08:51 UTC, tverhoken requested changes
Nice job here 😃 

A little refactoring maybe but it will be safer to have unit tests before doing so. I'm a little strict about project quality and tests so I can't let new behavior uncovered. I'm ok to help with it if you are not familiar about unit test practices.

2020-10-29 08:51 UTC, tverhoken commented on src/index.ts
> +  mapAllArgumentsToAnArray(args).forEach((element) => {
Maybe we could avoid looping over the entire array and use `.filter` or `.find` for both seeking arguments ?

2020-10-29 08:51 UTC, tverhoken commented on src/index.ts
> +  });
Something like :

```suggestion
branch = mapAllArgumentsToAnArray(args).find(argArray => argArray[0] === "branch");
branch = mapAllArgumentsToAnArray(args).find(argArray => argArray[0] === "path");
```

What do you think ?

We could also declare `branch` and `path` as `const`.

2020-10-29 08:51 UTC, tverhoken commented on src/index.ts
>  export default function run(commandArgs: string[]) {
For unit tests, we should add 2 tests that assert the default branch use for `exec` first arg and the provided argument when targeting another branch.

Same for the Stryker's configuration path.

Are you familiar with unit testing and mocks ? Or would you like an example with one of the test case involved ?

2020-11-20 09:55 UTC, tverhoken approved these changes

2020-11-20 09:56 UTC, tverhoken commented
Hi @PauloGoncalvesBH 

I allowed myself to push to your repo in order to make this PR go.

Feel free to look at commits I did and to contact me if you wanna exchange about it.

2020-11-20 09:56 UTC, merged